// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3JrZo0Yrr2t451bR3VRwIw9CaVQq-PmE',
    appId: '1:524468881293:web:e17ea2876cc68c64d51fc4',
    messagingSenderId: '524468881293',
    projectId: 'authentication-61e4d',
    authDomain: 'authentication-61e4d.firebaseapp.com',
    storageBucket: 'authentication-61e4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpy_MUCLO7Pa4B4YNYKWy1RvHmVUyXKw4',
    appId: '1:524468881293:android:dba602a4e5368b85d51fc4',
    messagingSenderId: '524468881293',
    projectId: 'authentication-61e4d',
    storageBucket: 'authentication-61e4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmY6RnBEg_S55FrQZVwNeAjDjcfot8oBk',
    appId: '1:524468881293:ios:031b73f563c2309ed51fc4',
    messagingSenderId: '524468881293',
    projectId: 'authentication-61e4d',
    storageBucket: 'authentication-61e4d.appspot.com',
    iosBundleId: 'com.example.wathiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmY6RnBEg_S55FrQZVwNeAjDjcfot8oBk',
    appId: '1:524468881293:ios:031b73f563c2309ed51fc4',
    messagingSenderId: '524468881293',
    projectId: 'authentication-61e4d',
    storageBucket: 'authentication-61e4d.appspot.com',
    iosBundleId: 'com.example.wathiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3JrZo0Yrr2t451bR3VRwIw9CaVQq-PmE',
    appId: '1:524468881293:web:36244589b3472cefd51fc4',
    messagingSenderId: '524468881293',
    projectId: 'authentication-61e4d',
    authDomain: 'authentication-61e4d.firebaseapp.com',
    storageBucket: 'authentication-61e4d.appspot.com',
  );

}